apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    application: kube-janitor
    version: v20.3.2
  name: kube-janitor
spec:
  replicas: 1
  selector:
    matchLabels:
      application: kube-janitor
  template:
    metadata:
      labels:
        application: kube-janitor
        version: v20.3.2
    spec:
      serviceAccountName: kube-janitor
      containers:
      - name: janitor
        # see https://github.com/hjacobs/kube-janitor/releases
        image: hjacobs/kube-janitor:20.3.2
        args:
          # dry-run disabled by default, remove comment only generate "would have" logs
          #- --dry-run
          # comment out to have less verbose logging
          - --debug
          - --rules-file=/config/rules.yaml
          - --include-resources=persistentvolumeclaims
          # Interval set high for testing to avoid looping quickly. Can also use as cron job "once" if we want. 
          - --interval=1200
        resources:
          limits:
            memory: 100Mi
          requests:
            cpu: 5m
            memory: 100Mi
        securityContext:
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 1000
        volumeMounts:
          - name: config-volume
            mountPath: /config
      volumes:
      - name: config-volume
        configMap:
          name: kube-janitor
